# Generated by Django 4.1.5 on 2023-01-07 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountHistoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_id", models.IntegerField()),
                ("amount", models.FloatField()),
                ("notes", models.CharField(max_length=10000)),
                ("currency_id", models.IntegerField()),
                ("account_operation_id", models.IntegerField()),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "account_history",
            },
        ),
        migrations.CreateModel(
            name="AccountingEventModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type_id", models.IntegerField()),
                ("fee_amount", models.FloatField()),
                ("currency_id", models.IntegerField()),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "accounting_event",
            },
        ),
        migrations.CreateModel(
            name="AccountingEventTypeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "accounting_event_type",
            },
        ),
        migrations.CreateModel(
            name="AccountingItemModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "accounting_item",
            },
        ),
        migrations.CreateModel(
            name="AccountOperationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_operation", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "account_operation",
            },
        ),
        migrations.CreateModel(
            name="AccountStatementModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_id", models.IntegerField()),
                ("category", models.CharField(max_length=100)),
                ("payment_date", models.DateField()),
                ("situation", models.CharField(max_length=100)),
                ("notes", models.CharField(max_length=500)),
                ("fee_amount", models.FloatField()),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "account_statement",
            },
        ),
        migrations.CreateModel(
            name="AccountTypeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_type_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "account_type",
            },
        ),
        migrations.CreateModel(
            name="AdditionalToolUserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("passport_number", models.CharField(max_length=100)),
                ("birth_date", models.DateField()),
                ("nationality", models.CharField(max_length=100)),
                ("telephone", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "addition_tool_users",
            },
        ),
        migrations.CreateModel(
            name="CategoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="CheckPaymentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_id", models.IntegerField()),
                ("check_number", models.CharField(max_length=100)),
                ("checking_account", models.IntegerField()),
                ("check_holder", models.CharField(max_length=100)),
                ("cash_time", models.DateField()),
                ("receipt_time", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "check_payment",
            },
        ),
        migrations.CreateModel(
            name="CompanyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "company",
            },
        ),
        migrations.CreateModel(
            name="ContractHistoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_id", models.IntegerField()),
                ("situation", models.CharField(max_length=500)),
                ("note", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "contract_history",
            },
        ),
        migrations.CreateModel(
            name="ContractModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_number", models.CharField(max_length=100)),
                ("company", models.IntegerField()),
                ("contract_for", models.CharField(max_length=100)),
                ("contract_status_id", models.IntegerField()),
                ("vehicle_id", models.IntegerField()),
                ("issue_date_and_time", models.DateTimeField()),
                ("rent_days", models.IntegerField()),
                ("return_date_and_time", models.DateTimeField()),
                ("issue_point", models.CharField(max_length=100)),
                ("return_point", models.CharField(max_length=100)),
                ("early_delivery_date", models.DateTimeField()),
                ("vehicle_issue_address", models.CharField(max_length=100)),
                ("vehicle_return_address", models.CharField(max_length=100)),
                ("customer_id", models.IntegerField()),
                ("payment_total_fee", models.FloatField()),
                ("debt", models.FloatField()),
                ("amount_paid", models.FloatField()),
                ("payment_currency", models.IntegerField()),
                ("agent_fee", models.FloatField()),
                ("agent_percentage", models.FloatField()),
                ("intermediary_company_account", models.IntegerField()),
                ("payment_completion", models.IntegerField()),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "new_contract",
            },
        ),
        migrations.CreateModel(
            name="ContractPaymentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_id", models.IntegerField()),
                ("contract_id", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "contract_payment",
            },
        ),
        migrations.CreateModel(
            name="ContractStatusModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_status", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "contract_status",
            },
        ),
        migrations.CreateModel(
            name="CreditCardPaymentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_id", models.IntegerField()),
                ("bank_pos_account", models.IntegerField()),
                ("bank_intermediation_fee", models.FloatField()),
                ("card_holder", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "credit_card_payment",
            },
        ),
        migrations.CreateModel(
            name="CurrencyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency_code", models.CharField(max_length=100)),
                ("exchange_rate", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "currencies",
            },
        ),
        migrations.CreateModel(
            name="CurrentAccountModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.IntegerField()),
                ("account_type_id", models.IntegerField()),
                ("account_name", models.CharField(max_length=100)),
                ("account_currency_id", models.CharField(max_length=100)),
                ("explanation", models.CharField(max_length=1000)),
                ("balance", models.FloatField()),
                ("contract_id", models.IntegerField()),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "current_account",
            },
        ),
        migrations.CreateModel(
            name="CustomerBlackListModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "customer_black_list",
            },
        ),
        migrations.CreateModel(
            name="CustomerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_id", models.IntegerField()),
                ("black_list", models.IntegerField()),
                ("customer_title", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("father_name", models.CharField(max_length=100)),
                ("mother_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("place_of_birth", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=100)),
                ("cell_phone_1", models.CharField(max_length=100)),
                ("cell_phone_2", models.CharField(max_length=100)),
                ("home_phone", models.CharField(max_length=100)),
                ("job", models.CharField(max_length=100)),
                ("student", models.IntegerField()),
                ("student_id", models.IntegerField()),
                ("business_phone", models.CharField(max_length=100)),
                ("office_phone", models.CharField(max_length=100)),
                ("business_address", models.CharField(max_length=100)),
                ("home_address", models.CharField(max_length=100)),
                ("local_address", models.CharField(max_length=100)),
                ("nationality", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("email_2", models.CharField(max_length=100)),
                ("passport_no", models.CharField(max_length=100)),
                ("blood_group", models.CharField(max_length=5)),
                ("license_number", models.CharField(max_length=100)),
                ("license_issue_date", models.DateField()),
                ("license_issue_place", models.CharField(max_length=100)),
                ("account_tl", models.IntegerField()),
                ("account_dollar", models.IntegerField()),
                ("account_euro", models.IntegerField()),
                ("account_pound", models.IntegerField()),
                ("system_note", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "customers",
            },
        ),
        migrations.CreateModel(
            name="CustomerTypeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "customer_type",
            },
        ),
        migrations.CreateModel(
            name="DefaultPaymentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_id", models.IntegerField()),
                ("account_id", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "default_payment",
            },
        ),
        migrations.CreateModel(
            name="ExpenseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_account_id", models.IntegerField()),
                ("accounting_item_id", models.IntegerField()),
                ("invoice_id", models.IntegerField()),
                ("payment_method_id", models.IntegerField()),
                ("currency_id", models.IntegerField()),
                ("fee_amount", models.FloatField()),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                ("exchange_rate", models.FloatField()),
                ("expense_category", models.CharField(max_length=100)),
                ("explanation", models.CharField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "expense",
            },
        ),
        migrations.CreateModel(
            name="FileTypeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_type", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "file_type",
            },
        ),
        migrations.CreateModel(
            name="FileUploadModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=255)),
                ("file_type_id", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "files",
            },
        ),
        migrations.CreateModel(
            name="FoundPaymentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_id", models.IntegerField()),
                ("cash_account", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "found_payment",
            },
        ),
        migrations.CreateModel(
            name="IncomeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paying_account_id", models.IntegerField()),
                ("accounting_item_id", models.IntegerField()),
                ("invoice_id", models.IntegerField()),
                ("payment_method_id", models.IntegerField()),
                ("currency_id", models.IntegerField()),
                ("fee_amount", models.FloatField()),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                ("exchange_rate", models.FloatField()),
                ("collection_category", models.CharField(max_length=100)),
                ("explanation", models.CharField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "income",
            },
        ),
        migrations.CreateModel(
            name="InvoiceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_date", models.DateTimeField(auto_now_add=True)),
                ("current_account_id", models.IntegerField()),
                ("accounting_item_id", models.IntegerField()),
                ("collection_date", models.DateField(auto_now_add=True)),
                ("currency_id", models.IntegerField()),
                ("invoice_number", models.CharField(max_length=100)),
                ("fee_amount", models.FloatField()),
                ("explanation", models.CharField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "invoice",
            },
        ),
        migrations.CreateModel(
            name="MailOrderPaymentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_id", models.IntegerField()),
                ("pos_account", models.IntegerField()),
                ("brokerage_fee", models.FloatField()),
                ("card_type_provider", models.CharField(max_length=100)),
                ("card_number", models.CharField(max_length=100)),
                ("card_holder", models.CharField(max_length=100)),
                ("cvc_code", models.CharField(max_length=20)),
                ("expiry_year", models.IntegerField()),
                ("expiry_month", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "mail_order_payment",
            },
        ),
        migrations.CreateModel(
            name="OperationStatusModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("op_status", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "operation_status",
            },
        ),
        migrations.CreateModel(
            name="OperationTypeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation_type", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "vehicle_operation",
            },
        ),
        migrations.CreateModel(
            name="PaymentForModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "payment_for",
            },
        ),
        migrations.CreateModel(
            name="PaymentMethodModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "payment_method",
            },
        ),
        migrations.CreateModel(
            name="PaymentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_method_id", models.IntegerField()),
                ("payment_status_id", models.IntegerField()),
                ("payment_for", models.IntegerField()),
                ("amount_fee", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "payment",
            },
        ),
        migrations.CreateModel(
            name="PaymentStatusModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "payment_status",
            },
        ),
        migrations.CreateModel(
            name="PlaceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "place",
            },
        ),
        migrations.CreateModel(
            name="PricingMethodModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pricing", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "pricing_method",
            },
        ),
        migrations.CreateModel(
            name="RegionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region_name", models.CharField(max_length=200)),
                ("zone_type", models.CharField(max_length=200)),
                ("upper_region", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "regions",
            },
        ),
        migrations.CreateModel(
            name="ReservationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reservation_status_id", models.IntegerField()),
                ("customer_id", models.IntegerField()),
                ("reservation_maker_id", models.IntegerField()),
                ("vehicle_id", models.IntegerField()),
                ("purchase_date", models.DateField()),
                ("pick_up_time", models.TimeField()),
                ("pick_up_place", models.CharField(max_length=100)),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                ("flight_number", models.CharField(max_length=100)),
                ("total_fee", models.FloatField()),
                ("currency_id", models.IntegerField()),
                ("vehicle_full_address", models.CharField(max_length=200)),
                ("vehicle_delivery_address", models.CharField(max_length=200)),
                ("vehicle_delivery_date", models.DateField()),
                ("vehicle_delivery_time", models.TimeField()),
                ("vehicle_return_place", models.CharField(max_length=100)),
                ("return_flight_number", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "new_reservation",
            },
        ),
        migrations.CreateModel(
            name="ReservationPaymentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_id", models.IntegerField()),
                ("reservation_id", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "reservation_payment",
            },
        ),
        migrations.CreateModel(
            name="ReservationStatusModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "reservation_status",
            },
        ),
        migrations.CreateModel(
            name="StopModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=2000)),
                ("region_id", models.IntegerField()),
                ("sequence_no", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "stops",
            },
        ),
        migrations.CreateModel(
            name="StudentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_number", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                ("school", models.CharField(max_length=100)),
                ("section", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "students",
            },
        ),
        migrations.CreateModel(
            name="SystemReminderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.CharField(max_length=20000)),
                ("reminder_type_id", models.CharField(max_length=1000)),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "system_reminder",
            },
        ),
        migrations.CreateModel(
            name="SystemReminderTypeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reminder_type", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "system_reminder_type",
            },
        ),
        migrations.CreateModel(
            name="TransferPaymentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_id", models.IntegerField()),
                ("transfer_account", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "transfer_payment",
            },
        ),
        migrations.CreateModel(
            name="UserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_type_id", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="UserTypeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "user_type",
            },
        ),
        migrations.CreateModel(
            name="VehicleBrandModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "vehicle_brand",
            },
        ),
        migrations.CreateModel(
            name="VehicleCapacityModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_passengers", models.IntegerField()),
                ("BV", models.IntegerField()),
                ("KV", models.IntegerField()),
            ],
            options={
                "db_table": "vehicle_capacity",
            },
        ),
        migrations.CreateModel(
            name="VehicleComponentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("component_name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "vehicle_components",
            },
        ),
        migrations.CreateModel(
            name="VehicleExpenseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_company_id", models.IntegerField()),
                ("vehicle_id", models.IntegerField()),
                ("invoice_id", models.IntegerField()),
                ("payment_method_id", models.IntegerField()),
                ("currency_id", models.IntegerField()),
                ("fee_amount", models.FloatField()),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                ("exchange_rate", models.FloatField()),
                ("expense_category", models.CharField(max_length=100)),
                ("explanation", models.CharField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "vehicle_expense",
            },
        ),
        migrations.CreateModel(
            name="VehicleHistoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_id", models.IntegerField()),
                ("operation_type", models.CharField(max_length=100)),
                ("explanation", models.CharField(max_length=500)),
                ("title", models.CharField(max_length=100)),
                ("operation_status_id", models.IntegerField()),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                ("user", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "vehicle_history",
            },
        ),
        migrations.CreateModel(
            name="VehicleMaintenanceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_id", models.IntegerField()),
                ("date_entry", models.DateTimeField(auto_now_add=True)),
                ("release_date", models.DateTimeField(auto_now_add=True)),
                ("explanation", models.CharField(max_length=1000)),
                ("amount", models.FloatField()),
                ("currency_id", models.IntegerField()),
                ("care_place", models.CharField(max_length=1000)),
                ("input_km", models.FloatField()),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "vehicle_maintenance",
            },
        ),
        migrations.CreateModel(
            name="VehicleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_owner", models.CharField(max_length=100)),
                ("vehicle_model_id", models.IntegerField()),
                ("vehicle_plate_number", models.CharField(max_length=100)),
                ("traffic_release_year", models.IntegerField()),
                ("region_location", models.CharField(max_length=100)),
                ("vehicle_status_id", models.IntegerField()),
                ("vehicle_status", models.CharField(max_length=100)),
                ("rent_start", models.DateTimeField()),
                ("rent_end", models.DateTimeField()),
                ("input_km", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "vehicles",
            },
        ),
        migrations.CreateModel(
            name="VehicleModelModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_type_id", models.IntegerField()),
                ("vehicle_model", models.CharField(max_length=100)),
                ("number_of_doors", models.IntegerField()),
                ("vehicle_price_class_id", models.IntegerField()),
                ("model_year", models.IntegerField()),
                ("fuel_type", models.CharField(max_length=100)),
                ("gear", models.CharField(max_length=100)),
                ("large_suitcase", models.IntegerField()),
                ("small_suitcase", models.IntegerField()),
                ("number_of_passengers", models.IntegerField()),
                ("components", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "vehicle_model",
            },
        ),
        migrations.CreateModel(
            name="VehiclePaymentReminderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_id", models.IntegerField()),
                ("payment_date", models.DateField(auto_now_add=True)),
                ("fee_amount", models.FloatField()),
                ("explanation", models.CharField(max_length=20000)),
                ("currency_id", models.IntegerField()),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "vehicle_payment_reminder",
            },
        ),
        migrations.CreateModel(
            name="VehiclePriceClassModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price_class", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "vehicle_price_class",
            },
        ),
        migrations.CreateModel(
            name="VehicleStatusModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "vehicle_status",
            },
        ),
        migrations.CreateModel(
            name="VehicleTypeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_name", models.CharField(max_length=100)),
                ("max_num_of_person", models.IntegerField()),
                ("max_small_suitcase", models.IntegerField()),
                ("max_large_suitcase", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "vehicle_type",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(default="default.jpg", upload_to="profile_pics"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "profile",
            },
        ),
    ]
