# Generated by Django 4.1.5 on 2023-01-26 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_rename_image_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfileModel',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
