# Generated by Django 4.1.5 on 2023-02-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='vehiclehistorymodel',
            name='explanation',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='vehiclehistorymodel',
            name='operation_type',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='vehiclehistorymodel',
            name='title',
            field=models.CharField(max_length=2500),
        ),
    ]
