# Generated by Django 4.1.5 on 2023-02-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_alter_profile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_logo',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='default_currency',
            field=models.CharField(default='TR', max_length=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='default_language',
            field=models.CharField(default='en', max_length=5),
        ),
    ]
